---
title: "コーヒーの紡ぐ思い出 / I fili del caffè"     
author: "ruca"
date: "2026-09-14"                                   
categories: [Saggio]
---

```{=html}
<style>


h1, h2, h3 {
  color: #2c302e !important;
}

body {
  background-image: none !important;
  background-color: #fafafa !important;
}

</style>
```
<p>

瞼を閉じていても眩しい。

<br>

障子を通した柔らかい光が、肌を照らす。

<br>

ゴリゴリとリビングから聞こえてくる音。<br> その音は、いまローマの小さい白い部屋で響いている。

</p>

<p style="text-align: center; color: #888;">

\-

父がコーヒーを始めたのは、私が小学生の頃だったように思う。

<br>

ポーレックスのマニュアルグラインダー。<br> ミルクは手持ちの小さいフォーマーだった。

<br>

ゴリゴリ、ゴリと時々引っかかりながらも進んでいく音。

<br>

それが、ウィーーンという音に変わる。

<br>

ミルクを泡立てたら、白くて少し背のある磁器のマグに注いで出来上がりだ。

<br>

「あ、おはよう」

<br>

私がベッドから起き上がる頃には、いつももうそのマグのコーヒーは半分くらいになっていた。<br> 香ばしく鼻をつくその香りに誘われ、眠い目をこすりながら起きるのが、私の朝だった。

</p>

<p>

昔はエスプレッソマシンはうちにはなかったはずだ。

<br>

朝からハンドドリップしていたのだろうか。

<br> また父に聞いてみようと思う。

<br>

たまに早く起きた朝や週末は、私もゴリゴリと動かしていた。<br> 細長く、上蓋が意外と抜けやすいあの銀色のポーレックス。

<br> 私は今よりずっと小さい手で、黄色いラバーの滑り止めを重ね、左手を胸の前に固定し、右手でハンドルを握り力強く回していく。

<br>

手首が軋む。

<br>

先週、この小さなローマの部屋で50グラムの浅煎り豆を挽いたときも、相変わらず手首が軋んだ。

<br>

手はずっと大きくなったのに、細長い筒を握ると力が入れづらいし、浅煎りで硬い豆のせいでなかなか簡単にハンドルが回らない。

<br>

そうだ、何かゴムのものはないか、とたまたまあった茶色のラバー鍋敷きで覆って掴んでみる。

<br>

大変握りにくい。

<br>

実家の黄色のラバーは薄手だったが、鍋敷きなので少し分厚く逆に手が滑ってしまう。

<br>

いよいよ諦めて、素手で掴み、ゴリゴリと続ける。

<br>

夏はすっきりコールドブリューだ、と思い挽き始めた豆。<br> 挽き終わる頃にはこめかみが汗ばんでいた。

</p>

<p style="text-align: center; color: #888;">

\-

\-

</p>

<p>

冷蔵庫を開けると、ぽんと佇むビーカーに入ったエスプレッソ。

<br> 大学生になると、 父が仕事に出てから起きる日も増えていった。<br> 朝一番の通学がないと、10代の頃のように毎朝同じように早く起きることがなくなってしまった。

<br>

プシューと響くミルクをスチームする音。

<br>

十数秒続くその音を横目に二度寝した記憶。

<br> 次に目が覚めて冷蔵庫を開けると、<br> キン、と冷やされたエスプレッソ。

<br>

ビーカーにそのままポンと氷を二個いれて、ステンレスのストローで飲む日もあれば、半分をミルクに注ぎ、半分に水を足しそのままアメリカーノで。

</p>

<p>

ある日はカヌレと。

<br>ある日はベーグルと。

<br>

やる気のない朝も、浅煎りの弾けるような苦さと酸っぱさが、なんとか足を動かし、手を動かす気力をくれた。

<br>

たまに飲み残しておいて、夜にカフェラテで。

<br>

すっかり忘れてしまい、次の日に。

<br> そんなこともあった。<br> それでも毎日そこにあるひんやりしたグラスが、ビーカーが、確かにわたしに与えてくれたものがあった。

</p>

<p style="text-align: center; color: #888;">

—

</p>

<p>プシューと響く音。</p>

<p>

真っ白の狭い部屋でキッチンに立つわたしは、この手で毎朝カフェラテを淹れる。

<br> まずはお湯を走らせ、ポルタフィルターとマグを温める。<br> 水滴を拭き上げ、コーヒーをぎゅっと押し込み溢れ出すエスプレッソ。

<br> 次はミルクをスチーム。<br> まったりしたサルデーニャ牛乳。さらっとしたラツィオ牛乳。

<br> 同じ時間空気を入れても、うまくスピンさせ、ラテアートをかけるようになる粘度にしあげるのは難しい。

<br> お気に入りのサルデーニャ牛乳が売り切れのときは、腕を上げるタイミング。<br> 空気入れをいつもより数秒長くして、ジャグがほんのり熱を帯び始めるのを手のひらで感じながら、まだもう少し入れるか？入れすぎか、頭の中は忙しい。

</p>

<p>

ラツィオ牛乳を試してから改めて気づく、サルデーニャ牛乳のまったりさ。ああ、やはりあの質感が恋しい。

<br> うまくスチームできても、注ぐ時のカップの傾けが弱い時もある。<br> 良いフォームができた時こそ、緊張して右手が震える。

<br> こん、こん、とジャグの底を打ち付けながら、ぐるぐる回しミルクを均一に保つ。<br> おっと、勢いよく回しすぎると溢れてしまう。

<br> 左手を傾け、ジャグの口をカップにぐっと近づける。

<br> クレマの浮かんだ焦茶色のエスプレッソに、広がっていく白。<br> 扇形に広がって行き、少し滲む白い線。

<br> ああ、今日は少し緩かった。

</p>

<p>

それでも、描ける時は訪れる。

<br> 思わず、息を呑み、やった、と呟いてしまう嬉しさをわたしは知っている。<br>

今日もわたしは一日を始めるラテを、淹れる。

</p>
