---
title: "書くこと / Essayer de m’écrire "     
author: "ruca"
date: "2026-10-04"                                   
categories: [Saggio]
---

```{=html}
<style>


h1, h2, h3 {
  color: #2c302e !important;
}

body {
  background-image: none !important;
  background-color: #fafafa !important;
}

</style>
```
<br>

エッセイ。

フランス語で、essayer、試みること。

<br>

−

書きたいという思いは、いつからかあった。

言葉という、色も匂いも動きもないものだけで、吸い込まれるような感覚。

幼い頃に、それを経験して以来、どうかいつか自分もできないだろうか、というような望みのような祈りのような気持ちがあった。

それでも、ペンを持って紙をもって試したことはなかった。

なぜだかはわからない。

多分、ひたすら日々に追われ、追いかけられ、

一息ついて、自分の中（うち）にあるものに形づけることなど許されていなかったからかもしれない。

<br>

ひとりで暮らしていると、いろいろな思いが溢れてくる。

<br>

日本にいれば、家族や友達に、日々の思いを少しずつ零し、溢れにくい気がする。

でも、ここにいると、毎日のようにひとと話すわけではないし

たまに外に出すことを試みても、イタリア語では紡ぎきれない。

<br>

そんな万感の思いを、したためるための場所があるといいかもしれない。

そう思って始めたのが、イタリアのことを綴るブログだった。

<br>

はじめは留学生の助けになれば、と思い始めたブログだったが、

助けられてきたのは、私だったかもしれなかった。

<br>

SPQR日記というものをはじめてから、

書くために紙とペン片手に街に繰り出した。

<br>

こころのなかにあったもやもや、なんとなく感じた視線、

細かくて、自分でも気にしているのか気にしていないのか、わからないきもち。

<br>

形づけるということは、

そこに形のないものに形を与えること、もうなんとなく形のあったものを、

思い込みで形を変えてしまうことかもしれない。

<br>

そんな少しのおそれを拭いきれずとも、やはり自らの中を形づけるという試みは、わたしの大切な営みとなった。
