---
title: "本屋さん / Libreria"     
author: "ruca"
date: "2026-10-05"                                   
categories: [Aneddoto]
---

```{=html}
<style>

h1, h2, h3 {
  color: #2c302e !important;
}

body {
  background-image: none !important;
  background-color: #fafafa !important;
}

</style>
```








<br>

日本の作家の本を、イタリアの本屋で見かけることが多い。

なんなら特集コーナーみたいな、わざわざ特別な一角の売り場が捧げられていることも少なくない。

<br>

日本では見たこともないような作家の本が続々と翻訳されている気がする。

私が知らないだけかもしれない。

<br>

いつものヴィエノワズリーを買いに行く道で少し涼もう、と本屋さんに久しぶりに入った。

<br>

癖で、ここはどの漱石を置いてるんだ、とコーナーを探す。

<br>

いつまで経っても、Sで探すのかNで探すのか確信が持てない。

棚の端から端までなぞるように視線を走らせ、「anima」を見つけた。

坊ちゃん、こころ、それから、門、吾輩は猫である、があった。

まあ、よくあるラインナップ。

<br>

ん？

「Piccoli racconti di un’infinita giornata primavera」。

見たことがない。しかも日本語でどの作品かピンとこない。

調べてみると、大好きな夢十夜と一緒に出された、「永日小品」だという。

<br>

やるじゃん。

<br>

その横に薄ーく挟まっている白い背表紙を見つけ、手に取ると

谷崎潤一郎の陰翳礼讃。

<br>

おお！訳されていたのか、そういえばこんないい本もあったな。
昔、兄に貸してもらった、しっとりとしたいい本だったと思い出す。

ただ、イタリア語タイトルを見ると

「Libro d’ombra」。

<br>

んー、本当にその訳でいいのか。礼讃をあらわすのは難しいのか。

また、どうも日本作品は適当な日本風の絵の表紙をつけられていて、どこか興醒めする時も多い。

でも、並んでいる漱石を見るだけでどこか安心する。ありがとう。

<br>

売り切れないうちに行かないと、と思い出し、焼きたてパンオショコラを手に入れるべく、いつもの路に戻った。
