---
title: "タルトシトロンの再発見 / La redécouverte de la tarte au citron"  
author: "ruca"
date: "2026-10-06"                                   
categories: [Aneddoto]
---

```{=html}
<style>

h1, h2, h3 {
  color: #2c302e !important;
}

body {
  background-image: none !important;
  background-color: #fafafa !important;
}

</style>
```
<br>

まだ、長袖か半袖か迷う季節だった。

3月に北極に関するフォーラムがあった。

ボランティアをすれば、空き時間は全ての講演を見ることができると偶然知り、

これは参加したいと思い迷わず申し込んだ。

<br>

フォーラムの前日、事前にホールの場所などの確認のために集合。

Ciao、と挨拶して、もうなんとなくできていた数人の輪に入る？

「ローマで何してるの？大学？」

意外と同じ年齢くらいの人達が5人くらいいて、お互いの専攻などを聞き合い、一気に打ち解けた。

<br>

右隣にいた、笑い顔のその子は、

「僕は、ローマを旅行中なんだ。」

え、旅行中に丸二日間ボランティアしてるのか。

「凄いね。」

どうも北極が好きらしく、近々アイスランドに旅行するらしい。

ノルマンディー出身で、いまはデンマークで建築を勉強しているらしい。

まあ、旅行のいい思い出になるのかな。

<br>

<br>


2日目の、現代美術館で行われたクロージングパーティーは、

大好きな美術館のひとつで、下から上までずらっと絵に囲まれた空間だった。

<br>


「Campari飲んだことある？苦いけど私のフランス人の教授がすごく好きだったの。」

「いや、ない。じゃあ次取る時注文してみる」

<br>

彼を含めた複数人と、同じ歳くらいの北極への愛や知識に溢れた人達と、

美味しいおつまみを片手に言葉を交わした。

<br>

特にその彼は、なんとなく何を言っても笑顔な感じで、

自分がフランス語を何も覚えていないのが悔やまれる。

<br>

「フランス語、すこしは勉強したのに忘れちゃった」

「でも、イタリア語できるのがすごいよ。僕もイタリア語勉強したいとは思ってるんだけど」

<br>

もうひとり居たポーランド出身だというシエナに住んでいる彼は、

フランス語を少しできるようで、2人は盛り上がる。

<br>

ああ、なんで覚えてないんだ！
悔しい。

言語がわからないときの、あの独特の感情は、少し久しぶりだった。

<br>

「それにしても、フランスはスイーツという財産が本当に素晴らしい。

私はフランスのスイーツが大好き。」

「ああ、そうなの？」

彼は、そんなに好きなのか、と少し乾いた感じで笑う。

<br>

「ねえ、カヌレの歴史なんて知ってる？美味し過ぎるスイーツのひとつだけど」

大学生の頃、カヌレに目がない時期があって、関西中のカヌレを食べ尽くしたかもしれない。

<br>

「いや、知らない知らない！」

なんなんだこの人は、と言わんばかりのさらに乾いた感じの笑い顔。

<br>

そこで私はカヌレの生まれた経緯を説明して、

ボルドーで口にしたカヌレが、どれほど甘くて香ばしくて、

夢のようだったかを話した。

<br>

「本当に君は面白いね。そんなにカヌレ好きなんだ。」

<br>

まさかローマのボランティアで、カヌレの歴史について、

フランスのスイーツについて、ここまで熱弁されるとは思ってなかっただろう。

声を出して彼は笑った。

<br>

「でも、僕はタルトシトロンの方が好きかな」

<br>

神戸にあったフランスお菓子のお店が頭をよぎる。

<br>

わ、タルトシトロンってあったな。
どんな味だっけ？はっきりと思い出せない。

<br>


そんなまま、私たちはみんなパーティーの喧騒に流れるように解散し、さよならさえ言えなかった。

その後、メッセージで、さよなら言えなかったね、と話した。

<br>

「また、タルトシトロンを食べにフランスにきたら知らせてね！楽しかったよ、良い夜を」

<br>

彼はいま、私がローマにあるフレンチカフェで毎週のように

タルトシトロンを手に入れて、日常を生きていることを知らないだろう。

フランス語だってそれから勉強し、すこしは使えるようになった。

<br>

最近は甘すぎるスイーツから、少し距離を感じていた。

そんな中、甘酸っぱいタルトシトロンが、疲れを癒してくれる味になった。
